create table if not exists public.parking_readings (
  id bigint generated by default as identity primary key,
  total_spaces integer not null check (total_spaces >= 0),
  free_spaces integer not null check (free_spaces between 0 and total_spaces),
  occupied_spaces integer not null check (occupied_spaces = total_spaces - free_spaces),
  spaces jsonb not null default '[]'::jsonb,
  source text not null default 'detector',
  captured_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists parking_readings_captured_at_idx
  on public.parking_readings (captured_at desc);

alter table public.parking_readings enable row level security;

revoke all on table public.parking_readings from anon, authenticated;
grant select, insert on table public.parking_readings to service_role;
grant usage, select on sequence public.parking_readings_id_seq to service_role;

comment on table public.parking_readings is
  'Historico de ocupacao enviado pelo detector SmartParking.';
